
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author onurh
 */
public class SiparisUygulamasi2 extends javax.swing.JFrame {
    Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>();
    /**
     * Creates new form SiparisUygulamasi2
     */
    public SiparisUygulamasi2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        beyti = new javax.swing.JCheckBox();
        salata = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("MENÜ");

        iskender.setText("İskender -  15 TL");

        beyti.setText("Beyti - 12 TL");

        salata.setText("Salata - 5 TL");

        ayran.setText("Ayran - 2 TL");

        goster.setText("Siparişleri Göster");
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goster, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(ayran)
                    .addComponent(salata)
                    .addComponent(beyti)
                    .addComponent(iskender)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(iskender)
                .addGap(49, 49, 49)
                .addComponent(beyti)
                .addGap(54, 54, 54)
                .addComponent(salata)
                .addGap(45, 45, 45)
                .addComponent(ayran)
                .addGap(52, 52, 52)
                .addComponent(goster, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void siparisleriGoster(){
        String message = "";
        int tutar = 0;
        
        if (siparisler.isEmpty()) {
            message = "Siparişiniz bulunmamaktadır." ;
        }
        else{
            message += "***Siparişler***\n";
            
            for(Map.Entry<String,Integer> entry : siparisler.entrySet()){
                message += entry.getKey() + "\n ";
                tutar += entry.getValue();
            }
            message += "Toplam Tutar : " + tutar;
        }
        JOptionPane.showMessageDialog(this, message);
        
    }
    
    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed
        // TODO add your handling code here:
        if(iskender.isSelected()){
            siparisler.put("İskender", 15);
        }
        else{
            siparisler.remove("İskender");
        }
        
        if(beyti.isSelected()){
            siparisler.put("Beyti", 12);
        }
        else{
            siparisler.remove("Beyti");
        }
        
        if(salata.isSelected()){
            siparisler.put("Salata",5);
        }
        else{
            siparisler.remove("Salata");
        }
        
        if(ayran.isSelected()){
            siparisler.put("Ayran",2);
        }
        else{
            siparisler.remove("Ayran");
        }
        
        siparisleriGoster();
    }//GEN-LAST:event_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox beyti;
    private javax.swing.JButton goster;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salata;
    // End of variables declaration//GEN-END:variables
}
